class_name GameAudio
extends RefCounted

# Original, short cues generated by Sounds/Generated/generate_audio.py.
const STEP_TILE: Array[AudioStream] = [
	preload("res://Sounds/Generated/step_tile_1.wav"),
	preload("res://Sounds/Generated/step_tile_2.wav"),
	preload("res://Sounds/Generated/step_tile_3.wav")
]
const STEP_METAL: Array[AudioStream] = [
	preload("res://Sounds/Generated/step_metal_1.wav"),
	preload("res://Sounds/Generated/step_metal_2.wav"),
	preload("res://Sounds/Generated/step_metal_3.wav")
]
const STEP_DEBRIS: Array[AudioStream] = [
	preload("res://Sounds/Generated/step_debris_1.wav"),
	preload("res://Sounds/Generated/step_debris_2.wav"),
	preload("res://Sounds/Generated/step_debris_3.wav")
]
const GRAB: AudioStream = preload("res://Sounds/Generated/grab.wav")
const RELEASE: AudioStream = preload("res://Sounds/Generated/release.wav")
const SCRAPE: AudioStream = preload("res://Sounds/Generated/scrape.wav")
const CARD_SWIPE: AudioStream = preload("res://Sounds/Generated/card_swipe.wav")
const TERMINAL_KEY: AudioStream = preload("res://Sounds/Generated/terminal_key.wav")
const BREAKER: AudioStream = preload("res://Sounds/Generated/breaker.wav")
const ACCESS_GRANTED: AudioStream = preload("res://Sounds/Generated/access_granted.wav")
const ACCESS_DENIED: AudioStream = preload("res://Sounds/Generated/access_denied.wav")
const DOOR_LATCH: AudioStream = preload("res://Sounds/Generated/door_latch.wav")


static func play_world(origin: Node2D, sound: AudioStream, volume_db: float = -10.0, distance: float = 260.0) -> void:
	if not is_instance_valid(origin) or sound == null or not origin.is_inside_tree():
		return
	var scene := origin.get_tree().current_scene
	var host: Node = scene if scene != null else origin
	var voice := AudioStreamPlayer2D.new()
	voice.bus = &"sfx"
	voice.stream = sound
	voice.volume_db = volume_db
	voice.max_distance = distance
	voice.attenuation = 2.0
	host.add_child(voice)
	voice.global_position = origin.global_position
	voice.finished.connect(voice.queue_free)
	voice.play()


static func play_ui(origin: Node, sound: AudioStream, volume_db: float = -12.0) -> void:
	if not is_instance_valid(origin) or sound == null or not origin.is_inside_tree():
		return
	var scene := origin.get_tree().current_scene
	var host: Node = scene if scene != null else origin
	var voice := AudioStreamPlayer.new()
	voice.bus = &"sfx"
	voice.stream = sound
	voice.volume_db = volume_db
	host.add_child(voice)
	voice.finished.connect(voice.queue_free)
	voice.play()
